name: dark_matter_page
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  firebase_analytics: ^11.4.2
  firebase_messaging: ^15.2.2
  cupertino_icons: ^1.0.8
  video_player: ^2.5.0 # Añadimos video_player para reproducir videos
  flutter_animate: ^4.5.2
  carousel_slider: ^5.0.0
  three_dart: ^0.0.16
  flutter_gl: ^0.0.21
  rive: ^0.13.20
  auto_size_text: ^3.0.0
  firebase_storage: ^12.4.2
  widget_and_text_animator: ^1.1.5
  photo_view: ^0.15.0
  animations: ^2.0.11
  google_fonts: ^4.0.4
  url_launcher: ^6.3.1
  flutter_staggered_grid_view: ^0.7.0
  mailer: ^6.4.1
  flutter_launcher_icons: ^0.11.0  # Usa la última versión
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  web:
    generate: true
  windows:
    generate: false
  macos:
    generate: false
  
  image_path: "assets/images/logob.webp"  # Ruta de la imagen del nuevo ícono

flutter:
  uses-material-design: true

  assets:
    - assets/images/github.webp
    - assets/images/nodejs.webp
    - assets/images/python.webp
    - assets/images/dart.webp
    - assets/images/flutter.webp
    - assets/images/logo.webp
    - assets/images/fondo.webm
    - assets/images/linkedin.webp
    - assets/images/instagram.webp
    - assets/images/tiktok.webp
    - assets/images/future.webp
    - assets/animate/logo.webm
    - assets/images/innovation.webp
    - assets/images/software_development.webm
    - assets/images/it_consulting.webp
    - assets/images/hardware_software.webp
    - assets/images/cybersecurity.webm
    - assets/images/ai_automation.webm
    - assets/images/experience.webp
    - assets/images/logob.webp
    - assets/images/soon.webp
    - assets/images/jade0.webp
    - assets/images/jade00.webp
    - assets/images/jade1.webp
    - assets/images/jade2.webp
    - assets/images/jade3.webp
    - assets/images/jade4.webp
    - assets/images/jade5.webp
    - assets/images/jade6.webp
    - assets/images/jade7.webp
    - assets/images/jade8.webp
    - assets/images/jade9.webp
    - assets/images/jade10.webp
    - assets/images/jade000.webp
    - assets/images/jadep.webp
    - assets/images/p00.webp
    - assets/images/pp0.webp
    - assets/images/p0.webp
    - assets/images/p1.webp
    - assets/images/p2.webp
    - assets/images/p3.webp
    - assets/images/p4.webp
    - assets/images/p5.webp
    - assets/images/p6.webp
    - assets/images/matter.webp
    - assets/images/dark.webp
    - assets/images/code.webp
    - assets/images/luna.webp
    - assets/images/l0.webp
    - assets/images/l1.webp
    - assets/images/l2.webp
    - assets/images/l3.webp
    - assets/images/l4.webp
    - lib/l10n/intl_en.json
    - lib/l10n/intl_es.json
