name: dark_matter_page
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  firebase_analytics: ^11.4.2
  firebase_messaging: ^15.2.2
  cupertino_icons: ^1.0.8
  video_player: ^2.5.0 # Añadimos video_player para reproducir videos
  flutter_animate: ^4.5.2
  carousel_slider: ^5.0.0
  three_dart: ^0.0.16
  flutter_gl: ^0.0.21
  rive: ^0.13.20
  auto_size_text: ^3.0.0
  firebase_storage: ^12.4.2
  widget_and_text_animator: ^1.1.5
  photo_view: ^0.15.0
  animations: ^2.0.11
  google_fonts: ^4.0.4
  url_launcher: ^6.3.1
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/background1.png
    - assets/images/background2.png
    - assets/images/github.png
    - assets/images/nodejs.png
    - assets/images/python.png
    - assets/images/dart.png
    - assets/images/flutter.png
    - assets/images/logo.png
    - assets/images/slide.mp4
    - assets/images/linkedin.png
    - assets/images/instagram.png
    - assets/images/tiktok.png
    - assets/images/future_image.png
    - assets/images/project1.png
    - assets/images/project2.png
    - assets/images/project3.png
    - assets/images/project4.png
    - assets/images/project5.png
    - assets/images/project6.png
    - assets/animate/logo.mp4
    - assets/images/innovation.jpg
    - assets/images/software_development.mp4
    - assets/images/it_consulting.jpg
    - assets/images/hardware_software.jpg
    - assets/images/cybersecurity.mp4
    - assets/images/ai_automation.mp4
    - assets/images/experience.jpg
    - assets/images/logob.png
    - assets/images/soon.jpg

