// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC54NRIqybT18oP9-xUpnECAQztYt52GdQ',
    appId: '1:372705593198:web:4265ec365357da3d18e37f',
    messagingSenderId: '372705593198',
    projectId: 'dark-60a60',
    authDomain: 'dark-60a60.firebaseapp.com',
    storageBucket: 'dark-60a60.firebasestorage.app',
    measurementId: 'G-QMHY7W0FV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcUu2iwpMVYGAINBHkU5O6orey0XRN7XE',
    appId: '1:372705593198:android:bedcf5850ce5817018e37f',
    messagingSenderId: '372705593198',
    projectId: 'dark-60a60',
    storageBucket: 'dark-60a60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0U1BKYmnIeCeUMHOoL_q2DAvP1ztfvTQ',
    appId: '1:372705593198:ios:464d5cc9bb936f9b18e37f',
    messagingSenderId: '372705593198',
    projectId: 'dark-60a60',
    storageBucket: 'dark-60a60.firebasestorage.app',
    iosBundleId: 'com.example.darkMatterPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0U1BKYmnIeCeUMHOoL_q2DAvP1ztfvTQ',
    appId: '1:372705593198:ios:464d5cc9bb936f9b18e37f',
    messagingSenderId: '372705593198',
    projectId: 'dark-60a60',
    storageBucket: 'dark-60a60.firebasestorage.app',
    iosBundleId: 'com.example.darkMatterPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC54NRIqybT18oP9-xUpnECAQztYt52GdQ',
    appId: '1:372705593198:web:0c3093cd43859ef418e37f',
    messagingSenderId: '372705593198',
    projectId: 'dark-60a60',
    authDomain: 'dark-60a60.firebaseapp.com',
    storageBucket: 'dark-60a60.firebasestorage.app',
    measurementId: 'G-91L06352Q4',
  );
}
